### PR TITLE
Add Russian localization

### PR DESCRIPTION
**Pull request by geraldus**
Note, I've bumped version of `base` dependency to **4.6** because of `readMaybe` function, I hope this is not very important.

Here is some questions:
1. why English translation of `SuccessCreate` in core package is lowercased while replace and update does not? [[1](https://github.com/lambdacms/lambdacms/blob/11e7a34881b03e9ac1530a10c01ef7c89fedff92/lambdacms-core/LambdaCms/Core/Message.hs#L149)]
2. what means "user is pending"? (I didn't get familiar with CMS yet, so it's unclear what is the best translation should be). Does it mean "user is not activated/verified yet"?

### CODE REVIEW

**Comment by matsrietdijk** [comment]
Hey @geraldus,
1. This seems like a typo, it should be uppercased.
2. "User is pending" does indeed mean that the user has not yet verified his/her account.

**Comment by geraldus** [comment]
@matsrietdijk hi!
I can make separate PR to fix that typo, or force push everything here.  What will you say?

Also, can you merge this #7 ?

**Comment by matsrietdijk** [comment]
@geraldus I will fix the typo on master, no pull request needed. I merged #7.

**Comment by geraldus** [comment]
@matsrietdijk ok, let me fix it in Russian translation in this case (I've followed english translations)

**Comment by geraldus** [comment]
I'm done, you can merge when Travis finish the job.

**Comment by cies** [comment]
Thanks a lot!

>  I've bumped version of base dependency to 4.6 because of readMaybe function, I hope this is not very important.

Should not be a problem, as we live ouy `stack-yaml` which prescribes (currently) a nightly right before the LTS-3.x serie came out, and thus prescribes `base 4.8.1.0`. 

I found 2 minor points (otherwise LGTM).

1) I think you miss capitalisation on this message: "на главную страницу"

2) You use bind to both `ru` and `ru-RU` but the second one is sometimes (twice) spelled as `ru-Ru` -- is that on purpose?

One final question: why do you bind both `ru` and `ru-RU`?  Maybe we should also do that for Dutch as we also have an `nl-NL`.

**Comment by geraldus** [comment]
@cies 
1) I've followed English translation, where this message also lowercased [[1](https://github.com/lambdacms/lambdacms/blob/master/lambdacms-core/LambdaCms/Core/Message.hs#L132)].  If this is a bug, I'll capitalize my translation, no problem (:
2) I've faced situations when some browsers send 'ru-RU' accept language header in request, without `ru-RU` case users will get wrong translation (I can't recall what browser had this behaviour, likely Chrome, but right now I can't reproduce this on latest Chrome and Safari on OS X).  So, this is just a habit.  And if I'm not wrong, second part followed by `-` should be capitalized.

**Comment by cies** [comment]
1) Sorry for not cross checking that. Not a bug.

2) I was looking into the difference between `ru-RU` and `ru-Ru` (see second lowecase) used in you PR. I'll have a look how Yesod i18n deals with fallbacks.

**Comment by geraldus** [comment]
@cies oh, thanks, it's a typo, will fix in few minutes!  As for second issue see http://www.yesodweb.com/book/internationalization (jump to **Message files** section).

**Comment by cies** [comment]
I think it is not necessary. In the docs we find that there is a fallback mechanism in `yesod-i18n`. :)

http://www.yesodweb.com/book/internationalization

Search for this string "pt-BR, es, he, pt".

To clarify myself, yesod-i18n will look for `ru` if your browser only asked for `ru-RU` and serve that if it exists.

**Comment by geraldus** [comment]
I'm done here too (:

**Comment by geraldus** [comment]
@matsrietdijk 
Can you also upload recent changes to Hackage, please?

**Comment by matsrietdijk** [comment]
@cies do you have time to upload to hackage today? I do not have my computer with me atm.

**Comment by cies** [comment]
I got into some yak-shaving regarding LambdaCms and I do not know when I find time to finish it off. So I'll not likely push changes soon.

I'm not sure if I want to supply a `stack.yaml`; currently a discussion on this topic here: https://www.reddit.com/r/haskell/comments/415vne/to_ship_stackyaml_or_not_to/

And I have also tweaked the Travis scripts quite a bit.

Finally I hope to get around moving the scaffolding/templates into `stack new` -- but I forsee some maintenance difficulties. Probably some scripts are needed for keeping the whole thing up-to-date with Yesod's scaffold templates.

**Comment by geraldus** [comment]
Ok, no problem, I configured my project to pick latest version from git.

**Pull request merged**
